name: newproject
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  data_connection_checker: ^0.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  http: ^0.13.3
  kiwi: ^3.0.0

dev_dependencies:
  kiwi_generator: ^3.0.1
  build_runner: ^2.1.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
